# Generated by Django 4.2.6 on 2023-10-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_product_app', '0002_alter_customuser_type_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='filename',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя_файла'),
        ),
    ]
